### ISSUE TITLE
Change syntax highlighting rules

### ISSUE THREAD

**Issue by aflyax** [IRkernel/IRkernel#149]
How do I add more items into list of certain keywords? (E.g., if I want 'print' to be highlighted, etc.) In IJulia there was a file I could do it in, but I can't find the same file or folder for IR.

Thanks!

**Comment by takluyver** [comment]
We don't define the syntax highlighting, we just tell the frontend to use the Codemirror mode for R:

http://codemirror.net/mode/r/index.html

**Comment by aflyax** [comment]
So, there is no way to redefine syntax highlighting by overriding rules?

**Comment by flying-sheep** [comment]
i guess you’ll have to use JS APIs of the [notebook](https://github.com/jupyter/notebook).

you can use [this stuff](https://github.com/jupyter/notebook/tree/master/notebook/static/notebook/js), which you load via AMD:

```js
require([
	'notebook/js/codecell',
	'codemirror/lib/codemirror',
], function(
	CodeCell,
	CodeMirror) {
	...
})
```

here is the [codemirror ipython mode](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/codemirror-ipython.js), i think that’s similar to the changes you want.

**Comment by takluyver** [comment]
The reason this was simple for IJulia was because Codemirror doesn't (didn't?) provide a mode for Julia, so they had to define their own mode anyway. Codemirror does include an R mode, so we just ask for that, there's no need to define our own. It's certainly possible to write JS to modify it, but I'm not exactly sure how, and those APIs aren't so stable.
