### ISSUE TITLE
'Undo' and 'Paste' are greyed out after IRKernel installation

### ISSUE THREAD

**Issue by elaOnMars** [IRkernel/IRkernel#187]
Hi, I have the recent development version of Jupyter ipython notebook which worked perfectly. The installation as a user for the IRKernel worked also. But I discovered, that in the 'Edit' tab of the ipython notebook the 'Undo' and 'Paste' buttons are greyed out and therefore not working anymore.

The development system is Debian 8 with the recent R and ipython versions.
Commit-Version should be 9c211c8902 as I installed the IRKernel with

$R

install.packages(c('rzmq','repr','IRkernel','IRdisplay'),repos = c('http://irkernel.github.io/', getOption('repos')),               type = 'source')

IRkernel::installspec()

As I do not know how to uninstall the IRKernel I cannot reproduce this error but I'd like to do.

**Comment by takluyver** [comment]
I'm pretty sure that installing a kernel can't affect those. But when you open a new notebook, those buttons will be greyed out, because there's nothing for it to undo, and nothing in its internal clipboard for it to paste.

Note that for now, the only thing it can undo is a single delete action, and Jupyter's clipboard mechanism is internal, independent of the system clipboard. This may lead to the buttons being greyed out when you're not expecting them to be. These are both things we hope to improve at some point.

**Comment by elaOnMars** [comment]
Thank you. Shall I remove the issue as it seems not to be an issue?

**Comment by takluyver** [comment]
No problem - I already closed the issue, there's no need to do anything else.
