### ISSUE TITLE
Issue with combining plotting

### ISSUE THREAD

**Issue by matthewgilbert** [IRkernel/IRkernel#190]
I am trying to stack multiple plots in the same graph, using something like

    set.seed(42)
    p1 <- hist(rnorm(500,4))
    p2 <- hist(rnorm(500,6))
    plot( p1, col=rgb(0,0,1,1/4), xlim=c(0,10))
    plot( p2, col=rgb(1,0,0,1/4), xlim=c(0,10), add=T)

which in the notebook gives me something like

![bug](https://cloud.githubusercontent.com/assets/2401026/10009134/33bf99e4-60a6-11e5-9f25-27fe84f07de0.png)

where as I would expect to see just the last image, which is what I get when entered in the R interpreter

![exp](https://cloud.githubusercontent.com/assets/2401026/10009155/82e6dd48-60a6-11e5-8fc0-f39ff215207a.png)

Am I missing something here? Is this expected behaviour?

**Comment by takluyver** [comment]
It's a bit tricky to tell when a new plot should be started with the R graphics machinery. We tried to use similar logic to knitr - does it behave as expected in knitr?

**Comment by matthewgilbert** [comment]
Ahh this has the same expected behaviour as in knitr, my mistake. My understanding on the R graphics machinery is pretty minimal but I thought possibly there was an issue as I was getting different outputs from the console than in a notebook.

**Comment by takluyver** [comment]
I probably would consider that a bug, but if knitr has the same bug, I don't know how we'd fix it.

Looking at the docs for `hist()`, it says "If `plot = TRUE`, the resulting object of class `histogram` is plotted by `plot.histogram`, before it is returned." Based on that, I think you should be creating your histogram objects by passing `plot = FALSE`, so that it doesn't try to plot them individually.

**Comment by flying-sheep** [comment]
well, that’s why i proposed to create our own plot device in #168.

it would simply record all low-level calls, which allows us to build a correct list of plots:

1. record calls
2. chunk calls into blocks that result in a separate plot each
3. replay the calls for each plot and each plot format (PNG, SVG, …) on a real device

**Comment by takluyver** [comment]
I think that's roughly what is already going on - as I understand it, the recordedPlot object we get from evaluate is something like a list of the low level drawing calls that are made. It's step 2, deciding what is a separate plot, that's non trivial.

![miracle](https://cloud.githubusercontent.com/assets/327925/10067924/351b005a-6298-11e5-8ceb-fce1f46369d1.gif)

However, I've looked a bit more at this particular case, and I don't think it is a bug after all. If you run those lines one-by-one in the R console, you do see each histogram plotted individually without colour first. If you run them all together, the last plot appears quickly enough that you don't see the two before it at all. In IRkernel, and in knitr, we intentionally show each plot created. If you don't want to see the other two, pass `hist(..., plot=FALSE)`.

**Comment by flying-sheep** [comment]
> as I understand it, the recordedPlot object we get from evaluate is something like a list of the low level drawing calls that are made.

that’s not true. what happens is specific to the device. so what we currently do is suboptimal since the recordedPlot object differs depending on which “host” device you use.

**Comment by JanSchulz** [comment]
IMO: the current benchmark (and probably for the time being the much more used case) is knitr. All the problems we have are probably also present in knitr (e.g. the usecases for `repr` is more or less the same as for the `asis` objects knitr invented, just that they didn't go all the way to record the output format, which is an argument to talk to the knitr guys and propose to merge these two approaches). In this case I think we should only build a new plotting device if knitr also uses it otherwise the benefits are not outweighing the drawbacks of building and maintaining such a device.

**Comment by flying-sheep** [comment]
let’s continue in #168

**Comment by flying-sheep** [comment]
@takluyver you’re right by the way. @matthewgilbert the fix is to do `hist(..., plot = FALSE)`
