### ISSUE TITLE
IRkernel failing due to segfault

### ISSUE THREAD

**Issue by a-paxton** [IRkernel/IRkernel#211]
After doing a fresh install of Jupyter and reinstalling IRkernel, I'm now unable to open my Jupyter notebook with IRkernel.  It's consistently failing due to segfault (see screenshot below).  I've confirmed that rzmq (which it's trying to call) is installed and accessible.  I've tried uninstalling and re-installing IRkernel and changing the user permissions, but no luck.  Any advice on this would be incredibly appreciated! 

<img width="682" alt="screen shot 2015-11-01 at 11 33 56 pm" src="https://cloud.githubusercontent.com/assets/9792532/10876383/0f9eb930-80f1-11e5-8783-9ae39e68d06a.png">

**Comment by takluyver** [comment]
Looks like the error is coming from rzmq. @armstrtw, any ideas what might cause a segfault or how to fix it?

**Comment by armstrtw** [comment]
The segfault looks like it occurred in init.context.

The code is here:
https://github.com/armstrtw/rzmq/blob/master/src/interface.cpp#L121

I suggest writing a small c++ program to see if this call succeeds on your machine:
zmq::context_t* context = new zmq::context_t(1);

Otherwise, it's going to be tough for me to duplicate.  Is IRkernel released as a deb package?

**Comment by takluyver** [comment]
> Is IRkernel released as a deb package?

Not as far as I know. Installation instructions are here: http://irkernel.github.io/installation/

**Comment by armstrtw** [comment]
I'm not really sure why init context would fail unless there is a problem w/ the libzmq installation.

If you want to check for it, then I suggest checking for a NULL return value here:
https://github.com/IRkernel/IRkernel/blob/master/R/kernel.r#L257

The reason I bring it up is that I see from the log @a-paxton postsed, it was restart attempt 4 of 5.  One thing I have noticed in the past, is that the behaviour of zmq becomes a bit strange when multiple contexts are initialized within the same program.  Since, IRkernel seems to be attempting restarts, multiple contexts are perhaps created, eventually resulting in a segfault...  Just a guess.

**Comment by takluyver** [comment]
That's the parent process restarting IRkernel - i.e. IRkernel dies, presumably because of this segfault, the parent process detects that and attempts to start it again. IRkernel should only be creating one zmq context per program. I don't think there's any point in IRkernel checking the return value - it looks like it's crashing before we'd get any return value to check.

**Comment by armstrtw** [comment]
Ok. I see.

I just put in a try/catch around  new zmq::context_t(1).  That should print out the error description if the context initialization fails.  @a-paxton,  Please try this new version. 

If you can't determine what is happening from the error description, then you'll have to start R w/ a debugger, and post the c/c++ stacktrace, but hopefully we don't have to go that deep.

**Comment by a-paxton** [comment]
Wow, thanks to everyone for such a quick turnaround!

I'm now having issues downloading rzmq in both R in Terminal and RStudio (see screenshots below).

<img width="703" alt="screen shot 2015-11-02 at 9 23 35 am" src="https://cloud.githubusercontent.com/assets/9792532/10888968/f5d8f012-8143-11e5-8f6b-061afc631146.png">

<img width="842" alt="screen shot 2015-11-02 at 9 25 57 am" src="https://cloud.githubusercontent.com/assets/9792532/10888985/fac200b4-8143-11e5-8abc-5b69b13ebce8.png">

I also get error messages when attempting to download per (1) IRkernel's install instructions and (2) <a href="http://www.michaelpacer.com/maths/r-kernel-for-ipython-notebook" target='_blank'>a third-party set of instructions that have served me well in the past</a>, which stores the repo locally and then installs from there.

(1)
<img width="913" alt="screen shot 2015-11-02 at 9 20 38 am" src="https://cloud.githubusercontent.com/assets/9792532/10889008/2afe9968-8144-11e5-80fe-d9666dd24421.png">

(2)
<img width="815" alt="screen shot 2015-11-02 at 9 33 17 am" src="https://cloud.githubusercontent.com/assets/9792532/10889093/cb459c28-8144-11e5-8be3-5d082a765477.png">

If any other information might help in debugging, please let me know!  Thanks again.

**Comment by takluyver** [comment]
The 'Library not loaded' errors are something we've seen quite a bit - we think it's some linking issue between rzmq and libzmq, but I don't properly understand it.

You seem to be getting segfaults from various unrelated things. Have you tried removing and reinstalling R itself?

**Comment by a-paxton** [comment]
Yeah, I did yesterday afternoon -- but I'll try it again and report back.

**Comment by armstrtw** [comment]
So...  The issue with install_github is that it doesn't respect git submodules.  So, that's basically not going to work.  you can do it from the command line.  I can walk you through it.  I had see some traffic on the zmq list about re-integrating the zmq.hpp project back into mainline, so hopefully that will happen soon. I think for the moment, I should move zmq.hpp back into rzmq, as submodules have proven to bee too complicated for people using dev_tools.

**Comment by a-paxton** [comment]
Okay, I found the problem.  After uninstalling R, I did a quick "which R" to confirm deletion, and it turns out that another instance of R had been downloaded through Anaconda (possibly through their "r-essentials" package meant to be used with IRkernel, although I'm not sure).  I removed the entire Anaconda directory then reinstalled R, Anaconda, Jupyter, and IRkernel (through the IRkernel instructions), and I'm good to go.  This makes me suspect it may have been an issue with conda's r-essentials not playing nicely with things.  Thanks so much for all the help!  I love IRkernel, and I'm absolutely thrilled that it's working again.

**Comment by takluyver** [comment]
Yes, conda has packages for R, and if that got installed, it could well conflict with a separately installed copy of R. I'm glad it works now.

**Comment by armstrtw** [comment]
ok. last comment...  I had introduced a bug with the try/catch fix earlier.  However, and more importantly, zmq.hpp is now embedded in the project, so install_github should now work...

**Comment by takluyver** [comment]
Thanks @armstrtw :-)
