### ISSUE TITLE
Can't input multibyte character within IRkernel of jupyter notebook?

### ISSUE THREAD

**Issue by zggjtsgzczh** [IRkernel/IRkernel#215]
I have win7. When I used jupyter notebook with R kernel running, I can't use chinese character within R code because of dead kernel. It gives me error message on terminal: 
***
[InstallKernelSpec] Installed kernelspec ir in C:\ProgramData\jupyter\kernels\ir
: lexical error: invalid char in json text.
***
And then, Kernel Restarting. The kernel appears to have died. It will restart automatically.
Can it be resolve? thanks

my code in IRkernel of jupyter notebook:
lsearching <- "行政法"
grep("行政法",lsearching)
***
R 3.1.1
win7
python 2.7
jupyter notebook

**Comment by flying-sheep** [comment]
can you give us the console output of the kernel?

**Comment by zggjtsgzczh** [comment]
To flying-sheep:
console output of the kernel error message:

[I 15:26:36.549 NotebookApp] Serving notebooks from local directory: E:\temp\pyt
hon_temp\
[I 15:26:36.549 NotebookApp] 0 active kernels
[I 15:26:36.549 NotebookApp] The IPython Notebook is running at: http://localhos
t:8888/
[I 15:26:36.552 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[I 15:26:55.016 NotebookApp] Kernel started: 6c9a8a8b-5273-444e-a051-645f51f8e67
f
[1] "Got unhandled msg_type:" "comm_open"
[InstallKernelSpec] Removing existing kernelspec in C:\ProgramData\jupyter\kerne
ls\ir
[InstallKernelSpec] Installed kernelspec ir in C:\ProgramData\jupyter\kernels\ir

: lexical error: invalid char in json text.
          arching <- \""\ngrep(\"",lsear
                     (right here) ------^

[I 15:27:10.017 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 6c9a8a8b-5273-444e-a051-645f51f8e67f restarted
[I 15:28:54.844 NotebookApp] Saving file at /Untitled1.ipynb

**Comment by flying-sheep** [comment]
the output seems to come from [YAJL](https://github.com/lloyd/yajl)

@lloyd any idea why this might happen?

**Comment by flying-sheep** [comment]
oh, and the fact that this already happens when installing the kernelspec shows that there’s probably something wrong with your installation of https://github.com/jeroenooms/jsonlite

**Comment by jeroenooms** [comment]
yajl/jsonlite should be fine, probably means the other end is generating invalid json.

**Comment by flying-sheep** [comment]
which means the jupyter notebook.

so something of this combination “win7, python 2.7, jupyter notebook” is probably at fault.

@zggjtsgzczh can you try with python3 and/or the newest version of both jupyter and notebook?

**Comment by takluyver** [comment]
I don't think this issue is in installspec. The only json that
installspec() should be reading is the kernel.json included with IRkernel,
and we'd know if that was invalid. In any case, OP already said the problem
occurred when he tried to run code containing a Chinese character. I guess
this will be an issue with serialising or deserealising non ASCII
characters (or possibly even non BMP characters) somewhere along the line
of JS-Python-R.

**Comment by jeroenooms** [comment]
It's probably a character encoding issue. Are you sure jupyter outputs UTF8 data? Because windows sometimes defaults to `ISO-8859-1` which is not valid for json.

**Comment by flying-sheep** [comment]
even more baffling is the installspec problem: we have an utf-8 file read using [fromJSON](https://github.com/IRkernel/IRkernel/blob/master/R/kernel.r#L338) and it still fails?

**Comment by jeroenooms** [comment]
Can you show me the file?

**Comment by flying-sheep** [comment]
it works on other systems, but here you go: https://github.com/IRkernel/IRkernel/blob/master/inst/kernelspec/kernel.json

**Comment by flying-sheep** [comment]
hmm, thinking about it, the error message is

```
[InstallKernelSpec] Installed kernelspec ir in C:\ProgramData\jupyter\kernels\ir
: lexical error: invalid char in json text.
```

i.e. the error probably happens after calling `kernelspec install`

@zggjtsgzczh can you tell us when those two lines occured and if there was other output

**Comment by takluyver** [comment]
Yeah, I think the kernelspec thing is a red herring, and the error is in
parsing the execute_request message.

Jupyter certainly should be transmitting json as utf-8. We're well aware of
the issues with relying on default encodings, and we're used to avoiding
that. But as none of the core team are regular windows users, it's always
possible that something has slipped in.

**Comment by jeroenooms** [comment]
I can't reproduce this problem though. Maybe OP should update his R version?

<img width="966" alt="capture" src="https://cloud.githubusercontent.com/assets/216319/11117511/ae677a74-893a-11e5-8fce-f4bdf6453b89.PNG">

**Comment by jeroenooms** [comment]
PS you should also add `Encoding: UTF8` to the IRkernel `DESCRIPTION` file because you have some non-ascii in the source code.

**Comment by flying-sheep** [comment]
good idea, done. i like putting non-ascii in comments (where it is completely harmless). R should really step up its game here and allow non-ascii literals and the like.

**Comment by flying-sheep** [comment]
@zggjtsgzczh: yeah, please update R, jupyter, and all relevant python packages like notebook and pyzmq.

then tell us if the error still occurs.

**Comment by jeroenooms** [comment]
@flying-sheep R does allow for that, you just need to specify if your source files are encoded in UTF8 or local encoding.

**Comment by flying-sheep** [comment]
R CMD check still complains though (and therefore such packages aren’t allowed on CRAN/BioConductor AFAIK)

**Comment by zggjtsgzczh** [comment]
First of all, thank for your attention above. Let to answer questions one by one.
I agree with **takluyver** about suspect to " line of JS-Python-R", because I 
can do it when convert to unicode through another python2.7 script code, such as:
[python code]
s="行政法"
dd=s.decode('utf-8')
dd
u'\u884c\u653f\u6cd5'
[python code]

and then, paste ***u'\u884c\u653f\u6cd5'*** into IRkernel running is OK. It maybe
a processing question of transmission while from jupyter into IRkernel.
***
I also agree with ***jeroenooms*** about issue that jupyter outputs 
default encodings. I tried to modify  ***kernel.json*** header, such as:
[kernel.json]
#Encoding:UTF8
{
  "argv": ["D:/R/R/R-3.2.2/bin/x64/R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R-3.2.2",
  "language": "R"
}
[kernel.json]
However, jupyter notebook does not work after launch, or where I did something wrong else.
***
About upgrade R this way, I did as mentioned code above you may saw still inextricability.
Perhaps, I should upgrade python2.7 into 3.x, because heard of python3.x change about encoding.
Whether affect to  scrpits edited in python2.7 running? Who know that?

Finally, flying-sheep, can you tell me, how to install the newest version of both jupyter
and notebook under kernel of python3.x? This version of jupyter notebook been installed 
for some time, thanks. :)

I cannot answer questions above timely with you because of time zone difference, thank for your
reply again.

**Comment by flying-sheep** [comment]
well, depends if you installed the python packages with pip or anaconda or something else.

anaconda: `conda update jupyter notebook`

pip: `pip install --upgrade jupyter notebook`

**Comment by jchevali** [comment]
This may be related.
I have an error originating in my Windows (Czech) system.
The error occurs upon startup, when either the web site or the console starts the R kernel.
The kernel-NNNN.json file is correct in content, but on my system it is located on a folder whose name contains special characters.
So to start the kernel, the full path to the file is given to R after the --args parameter, only, in this language, the path contains the string "Data aplikací" (ending in i-acute) instead of the usual "Application Data".
My workaround was to substitute DATAAP~1 into the APPDATA environmental variable prior to starting the kernel. I used the SET command in Windows to make sure the variable would contain DATAAP~1 instead of "Data aplikací" in the appropriate position, by the time I run the program.
Following that I can start the kernel without problem.

**Comment by jchevali** [comment]
Steps to reproduce:
- Use a Windows system where the Application Data folder is localized, such as Czech or posibly Catalan, or possibly an English system where the Windows username you've created to test contains special characters.
- From the Anaconda group in the Start Menu, launch the IPython Notebook, or launch the notebook or the console from the Windows Command line (if launching the console from the command line use a switch to set the kernel to ir)
- Once you've launched the Notebook, wait for the Web UI to load and select New -> R notebook in the upper right hand corner
- Verify how the R kernel dies and is unable to restart while the console window prints: Error: lexical error: invalid char in json text. C:\Documents and Settings\Admin (right here) ------^

Workaround:
Set the APPDATA variable in Windows so that the json filename passed to R won't have special chars, as done above, alternatively, modify the Windows shortcut, e.g.
* Before: C:\Anaconda\python.exe "C:\Anaconda\Scripts/ipython-script.py" notebook
* After: cmd.exe /k set "APPDATA=C:\Documents and Settings\YourUserNameHere\APPLIC~1" & C:\Anaconda\python.exe "C:\Anaconda\Scripts/ipython-script.py" notebook

Repeat for Jupyter

**Comment by takluyver** [comment]
Unicode characters in paths on Windows are a significant headache in Python 2 (it's better in Python 3). I wouldn't be surprised if there are similar issues in R, because I think R is more Unix-centric than Python, and the way Windows deals with unicode is completely different from how Unix deals with it.

**Comment by jeroenooms** [comment]
R is actually pretty good at this, it explicistly marks strings as `utf8` or `native` and converts when necessary. Can you point me to the `IRkernel` code that creates the R json string that is passed to `jsonlite::fromJSON()`?

**Comment by takluyver** [comment]
We're receiving raw vectors from rzmq (`receive.multipart`) and using `rawToChar()` on them here: https://github.com/IRkernel/IRkernel/blob/01376423ac7ad43dbd719172fa5edaea3e3f587c/R/kernel.r#L43-L46

**Comment by jeroenooms** [comment]
If the strings from python/zmq are in `utf8` you should mark them as such in R, otherwise R assumes they are native encoding. For example:

```r
test <- as.raw(c(0xe3, 0x81, 0x99, 0xe3, 0x81, 0x97))
str <- rawToChar(test)
Encoding(str) <- "UTF-8"
print(str)
```

**Comment by takluyver** [comment]
Yep, they are in UTF-8, as all JSON is supposed to be, IIRC. I think that might do the trick. I'll boot to Windows and have a fiddle.
