### ISSUE TITLE
Two [Out] per one [In] cell?

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/IRkernel#225]
As far as I know, in python you can only get one out for each in, but I just managed two outs for one in in R:

```
library(MatchIt) # load matching package
summary(lm(re78~treat,data=lalonde))
t.test(lalonde$re78[lalonde$treat==1],lalonde$re78[lalonde$treat==0],paired=FALSE)
```

![2015-12-09_141953](https://cloud.githubusercontent.com/assets/890156/11686304/fc9cc348-9e7f-11e5-8f99-eebc16e6bbfb.png)

I'm actually not sure what is better, but IMO it should be consistent...

**Comment by flying-sheep** [comment]
jup, we output everything, not just the last expression.

i think that fits R really well since R has `invisible()`, which can be used to

1. return things from functions invisibly, for the exact reason as to prevent it from showing accidentally
2. hide some output you want to hide.

you can just do `invisible(summary(...))` (although i don’t really understand why one would call `summary()` without assigning or displaying the result)

also R is pretty functional in design so this also makes sense. you rarely just call something for calling it, but usually for its return value.

**Comment by flying-sheep** [comment]
so i don’t think it should be done consistently across languages, as language REPLs behave differently and languages have different philosophies.

python | R
----|----
we have side effects | other than writing files, side effects are rare
we often ignore return values | we use or explicitly hide return values
we are OO and therefore mutate state of objects by calling methods | we have no bound methods* and are functional, so we use functions on handles or COW objects

*apart from ref classes

**Comment by takluyver** [comment]
I'm actually a bit surprised by that behaviour - I guess it's a consequence of the way evaluate handles things. It's our intention with the messaging protocol that `execute_result` messages are one per execution, though I guess we'll never strictly enforce that.

If we can send several of them, maybe they should be going as display_data instead of execute_result. Those message types are largely equivalent, but only execute_result results in the `Out[n]` prompt. The idea of those prompts comes from IPython making the result from an execution available for later code as `Out[n]`; since we don't do anything equivalent in IRkernel, it's arguably not important to show them.

**Comment by flying-sheep** [comment]
hmm, semantically, the way things are done now makes the most sense: there are multiple outputs per cell.

that there is only one in IPython seems to be an opinionated choice, as python doesn’t elsewise work like that (i.e. that the last statement in a block/function/code-unit is of special significance).

i think i prefer keeping things like they are, followed by using display_result, and wouldn’t like us to follow IPython here due to the language differences mentioned above.

**Comment by takluyver** [comment]
If you evaluated the cell as a block of code, though:

```
a = {
   cell contents...
}
```

a is only set to the last result.

I'm not terribly concerned either way, but it doesn't seem quite right to show multiple Out prompts.

**Comment by flying-sheep** [comment]
yup, in R it would work like that, sure. i was talking about python.

> I'm not terribly concerned either way, but it doesn't seem quite right to show multiple Out prompts.

ah, so that’s your gripe. can you say why?

**Comment by JanSchulz** [comment]
My preference:
1. only OUT (execution result) the returned value from the last line, every other returned value is omitted; plots are send as display_data
2. only OUT (execution result) the returned value from the last line, every other returned value and plots are sent as display_data
3. current behaviour: all returned values are sent as exec results; plots are send as display_data

I'm ok with the 1 and 2, but I find 3 not correct: IMO a "unit of code" as only one return value, not multiple. If there is something which uses the the r kernel as backend, kind of like `returned_value = kernel.execute(code)` then I expect that the last "returned" value ends up in the `retruned_value` and nothing else...

**Comment by takluyver** [comment]
I think that would be my preference as well, but I don't know how to make evaluate do something different with the last line.

**Comment by flying-sheep** [comment]
hmm, i’ve talked much already about *why* i prefer it the way it’s done now, so please reply to those points (explicit silencing mechanism, …)

**Comment by takluyver** [comment]
1. I don't think R is that different from Python in this respect. There are explicit mechanisms for displaying things (e.g. `print()`), and both have an implicit display of a single expression (via the 'visible' mechanism in R and 'displayhook' in Python). There's not much precedent for interactive UIs with cells like this (the normal interfaces for interactive R and Python being console based), so I think the best precedent is what IPython does.
2. The last expression in a block *does* have a particular significance in R, as demonstrated in my example above.
3. The Jupyter protocol and notebook UI were designed with an assumption that there is at most one `execute_result` message per execution, and at most one 'Out' prompt per 'In' prompt. I consider the fact that this works as it does to be somewhat accidental.

I've nothing particularly against showing results from every line, but I would make them `display_data` messages, which don't generate the 'Out' prompt, instead of `execute_result` messages.

**Comment by flying-sheep** [comment]
1. the visible mechanism isn’t global like the displayhook. it’s available in many functions everywhere
2. in a `{}` block, yes. which e.g. python doesn’t have
3. that’s a good point, we want to be good citizens. it should probably be specified in the protocol if it isn’t already.

about display_data: but as said, evaluate doesn’t give use info about which is the last statement. we’d have to either

* pre-parse the cell and feed the last statement separately from the others, or
* keep track of the last emitted output and decide what to do with it when either the next output or the end of the cell is reached.

**Comment by takluyver** [comment]
If it's not easy to treat the last statement differently, I'd just consider them all `display_data`, so there would never be `Out` prompts. The `Out` prompts are only really significant for IPython, in any case, because results are actually stored in a dictionary called `Out`.

In IPython we do actually separate out the last statement to run it in a slightly different way, but I don't really fancy trying to do the same with R unless there's a need.

**Comment by JanSchulz** [comment]
ok, this is also explained by the way evaluate works: it evaluates all complete expressions one by one:

```
text = "text"
text
text
```
results in:
```
Out[33]: "text"
Out[33]: "text"
```
but
```
{text = "text"
text
text}
```
results in:
```
Out[34]: "text"
```

Maybe we could submit a patch to evaluate to run all expressions in one go?

**Comment by JanSchulz** [comment]
I don't think this is a user question, but at least developer discussion :-)

Another way to fix this is submitting `"{" + code + "}"`. But that will result in more problems when some code prints something (will only be flushed at the end...).

So I think it's back to @takluyver to change all outputs to `display_data`: https://github.com/IRkernel/IRkernel/issues/225#issuecomment-164795794

**Comment by eric-wieser** [comment]
> As far as I know, in python you can only get one out for each in

Note that if you call `sys.displayhook` directly, then this ceases to be true

**Comment by flying-sheep** [comment]
ha, interesting! I think that’s a very uncommon thing to actually happen though, unlike displaying things in R. The problem here was that we didn’t know if jupyter’s protocol allows multiple [`execution_result`s](https://jupyter-client.readthedocs.io/en/stable/messaging.html#id6) per cell execution. Therefore it’s fair to expect frontends to only support one, and therefore it’s better to not emit multiple.

I guess since what you said is possible, we should clarify the language to state that multiple results per cell are possible, therefore making not supporting them a bug in the frontend.
