### ISSUE TITLE
Killing the kernel while it sends data is not killing the kernel completly

### ISSUE THREAD

**Issue by jankatins** [IRkernel/IRkernel#226]
With the current release (=without the "shorten the dataframe in print" fix), I printed a very big dataframe, which took more than a minute (didn't wait for it to finish). Before it finished, I killed the kernel via kernel -> restart kernel. The result was that this didn't work:
- I couldn't do anything afterwards, it looked like the new kernel was still in state "busy" -> executing cells, even only a `library(whatever)` didn't finish (cell has `*` instead of a number)
- in the process list, there were still a few processes left (the R kernel has 5 processes on windows)

**Comment by takluyver** [comment]
If it has started sending output to the frontend, the js may still be trying to process that output, which can block stuff happening in the browser. Can you reproduce this while it's doing some other long-running operation, or is it only when sending output?

**Comment by JanSchulz** [comment]
It seems that this is more a jupyter-client bug: IMO the [kernel manager](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L357) should [kill the complete process group](http://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true) and not only the process which is directly spawned by the kernel manager. 

I use restart kernel when I want resources back which I lost in the kernel (due to the stupid commands I executed) and currently I have a 4 processes running (cmd - R - cmd - Rterm) where I killed the kernel 15min ago (and it's still 25% CPU and 1GB Ram). So if I have to wait for the actual process which does the work to finish, the restart command is kind of useless :-(

cells to reproduce:

```
dat <- do.call(data.frame, replicate(8000, rep(FALSE, 8000), simplify=FALSE))
dim(dat)
dat[1,1]
head(dat)
# --- 
dat # and this takes ages...
```

**Comment by JanSchulz** [comment]
The other way could be to use Rterm instead of R:

```
{"argv": ["C:\\Program Files\\R\\R-3.2\\bin\\x64\\Rterm","-e","IRkernel::main()","--args","{connection_file}"],
 "display_name":"Rterm default"
}
```

This results in a single rterm process under the python of the notebook which gets killed in the middle of the dat printout...

(unfortunately, rterm is not in path :-( but if that path is [fixed at install time](https://github.com/IRkernel/IRkernel/blob/master/R/kernel.r#L338) then why not write the path to the `x64\rterm.exe`? [not sure how this is on linux/mac]

**Comment by JanSchulz** [comment]
I opened https://github.com/jupyter/jupyter_client/issues/104 for the kernel manager issue...

**Comment by takluyver** [comment]
Rterm does not appear to exist on my Linux install. [This SO answer](http://stackoverflow.com/a/3415135/434217) appears to say that it's a leftover, which implies it may not always be there.

**Comment by JanSchulz** [comment]
I suspect that the unresponsive notebook interface is simple that the browser got part of the output already and now tries to print it to the UI? If so it's probably  https://github.com/jupyter/notebook/issues/306

**Comment by takluyver** [comment]
Yeah, issues with overloading the browser by sending a lot of output are well known.

**Comment by JanSchulz** [comment]
@takluyver The answer is from 2010 and rterm is still there. :-)

There is also this comment:

> there is an important difference between R.exe and Rterm.exe - Rterm.exe is compiled with /LARGEADDRESSAWARE and can allocate 4 GB RAM when run under Windows 64 bit, unlike R.exe (we're talking about 32 bit R running under 64 bit Windows). Why would the R people do this only for Rterm.exe and not for R.exe, if Rterm.exe is obsolete?

**Comment by flying-sheep** [comment]
so it’s a jupyter-client bug.
