### ISSUE TITLE
spaces in front of unique output?

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/IRkernel#228]
When I use `unique(full_df$year)` or `names(full_df)`, I get ugly space in front of the list:

![2015-12-15_105553](https://cloud.githubusercontent.com/assets/890156/11807503/72ad1ef4-a31a-11e5-952f-2c92f3117883.png)

In the notebook, this is inserted as:
```
<div class="output_subarea output_html rendered_html output_result"><ol class="list-inline">
	<li>28418</li>
	<li>23651</li>
	<li>22405</li>
	<li>145671</li>
        <li>[...]</li>
</ol>
</div>
```

I've never seen such a "space" in python.

**Comment by JanSchulz** [comment]
Also:

Rstudio:
```
> unique(c(1,2,3,4,5,1,2,3,4,5))
[1] 1 2 3 4 5
```
notebook:
```
In [2]: unique(c(1,2,3,4,5,1,2,3,4,5))
Out[2]:      1 2 3 4 5
```

-> the "[1]" in front of the output is missing

**Comment by takluyver** [comment]
BTW, issues with the format of output are probably best filed on the repr repo, because that's what produces these data. I think @flying-sheep will see it either way, though.

I think the `[1]` index numbers on the left only really make sense in a fixed width environment where the process producing the output knows how it will be layed out. That's not currently the case with the HTML representation of vectors, because the numbers can be reflowed according to the browser window size. Maybe we can come up with some alternative way of conveying similar information, though.

**Comment by flying-sheep** [comment]
jup, that’s also the reason why i chose to use the `enumitem` package. there you can  configure if it’s important enough to see the index or not.

**Comment by flying-sheep** [comment]
but re-filing in repr seems like a good thing to do

**Comment by JanSchulz** [comment]
See https://github.com/IRkernel/repr/issues/22 Sorry for picking the wrong repo...
