### ISSUE TITLE
Failed to install rmzq in Cent OS 5 (-shared command not found)

### ISSUE THREAD

**Issue by gowthamnatarajan** [IRkernel/IRkernel#242]
I have everything installed and updated using Anaconda. I have R 3.2.0.
Running 
install.packages(c('rzmq','repr','IRkernel','IRdisplay'),
                 repos = c('http://irkernel.github.io/', getOption('repos')))

gives the following error:

make: [interface.o] Error 127 (ignored)
-shared -L/home/gowthan/Downloads/R-3.2.0/lib -L/usr/local/lib64 -o rzmq.so interface.o -lzmq -L/home/gowthan/Downloads/R-3.2.0/lib -lR
/bin/sh: line 2: -shared: command not found
make: *** [rzmq.so] Error 127
ERROR: compilation failed for package \u2018rzmq\u2019

What is the meaning of **-shared command not found**?

I get the same error even while trying to install from source.

**Comment by takluyver** [comment]
That looks like it's cut a command up half way through - `-shared` should probably be an option for another command, not the start of a command.

You may be able to get around it by installing rzmq using Anaconda - `conda install -c r r-rzmq`.

If that doesn't work, unfortunately I'm not really interested in trying to support Centos 5, when Centos 6 came out in 2011. And it sounds like an issue with rzmq rather than IRkernel itself, anyway.
