### ISSUE TITLE
Plots not working when running "jupyter console --kernel=ir"

### ISSUE THREAD

**Issue by randy3k** [IRkernel/IRkernel#262]
``` console
$ jupyter console --kernel=ir
Jupyter Console 4.1.0


In [1]: 1:10
Out[1]:  [1]  1  2  3  4  5  6  7  8  9 10

In [2]: plot(1:10)

In [3]: 

```

The plot command finished execution, but no graph is shown. I also manually triggered the quartz device, still no response.

``` r
In [3]: quartz()

In [4]: plot(1:10)

In [5]: 
```

Mac 10.11, Jupyter Console 4.1.0, iRkernel 0.5.

**Comment by takluyver** [comment]
It's sending the plots to the frontend, but the terminal console doesn't display images by default. You can configure it to do so with a [config option](http://jupyter-console.readthedocs.org/en/latest/config_options.html): `c.ZMQTerminalInteractiveShell.image_handler`.

We should probably also add an option in IRkernel to plot to an interactive backend rather than sending plots to the frontend.

**Comment by flying-sheep** [comment]
hmm, i wonder why our textual plot info doesn’t work though.

it should say [plot without title](https://github.com/IRkernel/repr/blob/master/R/repr_recordedplot.r#L43-L50) or so

**Comment by takluyver** [comment]
Curious...

**Comment by janschulz** [comment]
This is sent, so it seems that the console doesn't fall back?

[Add a `str(data)` in `display_data(...)`
```
In [1]: plot(1:10)
List of 3
 $ text/plain   : chr "plot without title"
 $ image/png    : raw [1:12628] 89 50 4e 47 ...
 $ image/svg+xml: chr "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlin"| __truncated__

In [2]:
```

**Comment by janschulz** [comment]
I added an upstream issue: https://github.com/jupyter/jupyter_console/issues/71

**Comment by randy3k** [comment]
It seems that the upstream bug has fixed, is there any chance to address this?

The R built-in console is terrible, I am looking forward to replacing it by running `jupyter console --kernel=ir`

**Comment by flying-sheep** [comment]
well, it works for me. still not for you?

```r
$ jupyter console --version
5.0.0
$ jupyter --version
4.2.0
$ R --slave -e 'sapply(c("repr", "IRdisplay", "IRkernel"), function(n) paste(packageVersion(n)))'
     repr IRdisplay  IRkernel 
   "0.10"   "0.4.4"   "0.7.1"
```

**Comment by randy3k** [comment]
No, nothing happens
```
(rmbpro)-~$ jupyter console --version
5.0.0
(rmbpro)-~$ jupyter --version
4.2.0
(rmbpro)-~$ R --slave -e 'library(magrittr);sapply(c("repr", "IRdisplay", "IRkernel"), . %>% packageVersion %>% paste)'
      repr  IRdisplay   IRkernel 
    "0.10" "0.4.9000"    "0.7.1" 
(rmbpro)-~$ jupyter console --kernel=ir
Jupyter console 5.0.0

R version 3.3.2 (2016-10-31)


In [1]: plot(1:10)

In [2]: 
```
macOS 10.12.1

**Comment by flying-sheep** [comment]
whoops, having magrittr in my .Rprofile doesn’t lead to reproducible code.

for me, a imagemagick window pops up.

this means that:

1. [`image_handler == 'PIL'`](https://github.com/jupyter/jupyter_console/blob/2e9035abb971f60073d7460b3cd7b3cd94668f6f/jupyter_console/ptshell.py#L164)
2. [`handle_image_PIL`](https://github.com/jupyter/jupyter_console/blob/2e9035abb971f60073d7460b3cd7b3cd94668f6f/jupyter_console/ptshell.py#L749) is called
3. `from PIL import Image, ImageShow` succeeds
4. PIL registered a [`DisplayViewer`](https://github.com/python-pillow/Pillow/blob/3.4.x/PIL/ImageShow.py#L159-L160) since i’m on linux and it found the `display` binary

```python
>>> import PIL
>>> PIL.VERSION
'1.1.7'
>>>  PIL.PILLOW_VERSION
'3.4.2'
>>> from PIL import ImageShow
>>> ImageShow._viewers
[<PIL.ImageShow.DisplayViewer at 0x7f577aceb2e8>]
>>> ImageShow._viewers[0].get_command_ex(None)
('display', 'display')
```

**Comment by flying-sheep** [comment]
for you, on OSX, [this should happen](https://github.com/python-pillow/Pillow/blob/3.4.x/PIL/ImageShow.py#L120-L126), so:

`ImageShow.MacViewer().get_command('myfile.png')` should return a runnable command.
