### ISSUE TITLE
display data not in sync

### ISSUE THREAD

**Issue by jankatins** [IRkernel/IRkernel#295]
from https://stackoverflow.com/questions/35786496/using-r-in-jupyter-display-markdown-in-loop

``` r
library(IRdisplay)
library(repr)
options(repr.vector.quote=FALSE)

for (i in 1:3) {
    print(paste("print before headline in run:",i))

    display_markdown(paste("# Headline in run:",i))

    cars <- c(i, 3, 6, 4, 9)
    plot(cars)   

    print(paste("print after headline in run:",i))
}
```

This is interesting, because the order is completely garbled (but stable)...

If I shorten that to 

``` r
library(IRdisplay)
library(repr)
options(repr.vector.quote=FALSE)

for (i in 1:3) {
    print(paste("print before headline in run:",i))

    #display_markdown(paste("# Headline in run:",i))

    cars <- c(i, 3, 6, 4, 9)
    plot(cars)   

    print(paste("print after headline in run:",i))
}
```

then knitr gets the order right, but we don't. So knitr does something better here than we are...

**Comment by janschulz** [comment]
I suspect two mechanism doing something wrong here:

* No stdout flushing -> remove by replacing print with message
* a bug somewhere in handling the plots

Using message gets the headline/prints into the right order, but the plots still are place in an odd ordering:

```
library(IRdisplay)
library(repr)
options(repr.vector.quote=FALSE)

for (i in 1:3) {
    message(paste("print before headline in run:",i))

    display_markdown(paste("# Headline in run:",i))

    cars <- c(i, 3, 6, 4, 9)
    plot(cars)   
    message(paste("print after headline in run:",i))
}
```

```
print before headline in run: 1
Headline in run: 1
print after headline in run: 1
print before headline in run: 2
Headline in run: 2
print after headline in run: 2
print before headline in run: 3
Headline in run: 3
<plot 1>
print after headline in run: 3
<plot 2>
<plot 3>
```

**Comment by takluyver** [comment]
I'd guess that part of it is the plot completion detection thing - we can't send a plot until the next plot is started, because we don't know if later code will add to the current plot (and it shouldn't be shown twice). I suppose we could queue up all output when there's a plot in waiting, and send it after sending the plot, but that seems like it's going to be more of a pain than it's worth.

Also, it looks like that's not the only ordering problem going on (if it was, I'd expect plot 1 to show up in plot 2's space).

**Comment by janschulz** [comment]
knitr works around this by using the working on the returned list of outputs -> it doesn't stream output as it becomes available.... It can even order plots which have text printed in between the plot calls...

[dreaming...]If the notebook would have the notion of overwriting output, this could be done by sending each plot when it becomes available and sending the same ID as long as the plots built on each other...[/]

I will add some more debugging messages and try to get an idea what's going on in the above code...

**Comment by takluyver** [comment]
knitr has a simpler situation to deal with, as I understand it - you only look at the output when it's completely finished, whereas in notebooks you expect to see output as it's produced (even if we don't do a brilliant job of that yet...)

ipywidgets does have a notion of addressable output widgets, but I think that's much more complexity than I want in IRkernel's base code for handling graphics. And I don't think they are displayed in order with other outputs, so we'd have to do all output through them, which I definitely don't want.

I think it would be a cool project for someone who understands something about R's graphics system to send data and have plots drawn in JS, rather than rendering them in the kernel and sending images; that would make some problems go away, though it comes with another set of problems, like what you save into the notebook file and how.

**Comment by janschulz** [comment]
Ok, this is the output of the following code on a current kernel, with a bit more debug statements included:


```R
options(jupyter.log_level = 3)
options(jupyter.logfile="jupyterrkernel.log")
library(IRdisplay)
library(repr)
options(repr.vector.quote=FALSE)

for (i in 1:5) {
    print(paste("print before headline in run:",i))

    display_markdown(paste("# Headline in run:",i))

    cars <- c(i, 3, 6, 4, 9)
    plot(cars)   

    print(paste("print after headline in run:",i))
}
```

Output:
```
Headline in run: 1
[1] "print before headline in run: 1"
Headline in run: 2
[1] "print after headline in run: 1"
[1] "print before headline in run: 2"
Headline in run: 3
<plot>
[1] "print after headline in run: 2"
[1] "print before headline in run: 3"
Headline in run: 4
<plot>
[1] "print after headline in run: 3"
[1] "print before headline in run: 4"
Headline in run: 5
<plot>
[1] "print after headline in run: 4"
[1] "print before headline in run: 5"
<plot>
[1] "print after headline in run: 5"
<plot>
```

Logging:
```
> IRkernel::main()
DEBUG: Sending msg display_data
INFO: Logging to jupyterrkernel.log
DEBUG: Stream output: [1] "print before headline in run: 1"

DEBUG: Sending msg stream
DEBUG: Sending msg display_data
DEBUG: Graphics output...
DEBUG: Stream output: [1] "print after headline in run: 1"
[1] "print before headline in run: 2"

DEBUG: Sending msg stream
DEBUG: Sending msg display_data
DEBUG: Graphics output...
DEBUG: Sending plot...
DEBUG: Sending msg display_data
DEBUG: Stream output: [1] "print after headline in run: 2"
[1] "print before headline in run: 3"

DEBUG: Sending msg stream
DEBUG: Sending msg display_data
DEBUG: Graphics output...
DEBUG: Sending plot...
DEBUG: Sending msg display_data
DEBUG: Stream output: [1] "print after headline in run: 3"
[1] "print before headline in run: 4"

DEBUG: Sending msg stream
DEBUG: Sending msg display_data
DEBUG: Graphics output...
DEBUG: Sending plot...
DEBUG: Sending msg display_data
DEBUG: Stream output: [1] "print after headline in run: 4"
[1] "print before headline in run: 5"

DEBUG: Sending msg stream
DEBUG: Graphics output...
DEBUG: Sending plot...
DEBUG: Sending msg display_data
DEBUG: Stream output: [1] "print after headline in run: 5"

DEBUG: Sending msg stream
DEBUG: Sending msg display_data
DEBUG: Sending msg status
DEBUG: Sending msg execute_reply
DEBUG: main loop: beginning
```

So, log and output aligns perfectly... -> the output is exactly how we got it from execute (minus the plots, which are always sent when the *next* plot shows up for the first time.).

But compareing code with output, the headlines for run 3 is too early:

```
Headline in run: 1 # before, because nothing has triggered any evaluate handling yet
[1] "print before headline in run: 1" # triggered by plot 1, which is not sent
Headline in run: 2  # again the sent before the print
[1] "print after headline in run: 1" # tiggered by plot 2
[1] "print before headline in run: 2" # tiggered by plot 2
Headline in run: 3 # ???? Should be after plot1?
<plot 1> # triggered by plot2
[1] "print after headline in run: 2" # tiggered by plot 3
[1] "print before headline in run: 3" # tiggered by plot 3
Headline in run: 4 # ??? 
<plot 2> # tiggered by plot 3
[...]
```

So the problem seems to be evaluate... At it seems to have something to do with loops: 

* unrolling the loop into just statements will be fine: evaluate will evaluate each statement and handle everything it encounters -> perfect order apart from the plots, which are always one plot late due to  "send on next new plot".
* Unrolling, but adding `{ ...}` around each block will also be fine: the end of the statement is now after each "loop run" and everything is outputted there -> the "after print" (triggered by end of statement) is now after the plot and before the headline and the "before print" (triggered by the next plot)
* Only when loops are introduced, the headlines do not fit in...

You can see this here:

```r
for (i in 1:5) {
    display_markdown(paste("# Headline in run:",i))
    cars <- c(i, 3, 6, 4, 9)
    plot(cars)   
}
```

This outputs:

```
Headline in run: 1
Headline in run: 2
Headline in run: 3 # to early, because p2 hasn't be handled yet
<plot 1> # triggered by p2
Headline in run: 4
<plot 2> # triggered by p3
Headline in run: 5
<plot 3> # triggered by p4
<plot 4> # triggered by p5
<plot 5> # triggered by end of statement
```

And this problem is also in visible if you use evaluate directly:

```
library(evaluate)

code <- "
for (i in 1:5) {
  print(paste('before:',i))
  txt(paste('call:', i),'call')
  cars <- c(i, 3, 6, 4, 9)
  plot(cars)   
  print(paste('after:',i))
}
"


l = list()
txt <- function(o, type) {
  t <- paste(o, collapse = '\n')
  l[length(l)+1] <<- t
}
oh <- new_output_handler(source = identity, 
                         text = function(o) txt(o, "text"), 
                         graphics = function(o) txt("plot", "plot"),
                         message = identity, 
                         warning = identity, 
                         error = identity, 
                         value = identity)


x <- evaluate(code, output_handler = oh)
l
```

This outputs:

```
> l
[[1]]
[1] "call: 1"

[[2]]
[1] "[1] \"before: 1\"\n"

[[3]]
[1] "call: 2" # <- too early...

[[4]]
[1] "plot"

[[5]]
[1] "[1] \"after: 1\"\n[1] \"before: 2\"\n"

[[6]]
[1] "call: 3"

[[7]]
[1] "plot"

[[8]]
[1] "[1] \"after: 2\"\n[1] \"before: 3\"\n"

[[9]]
[1] "call: 4"

[[10]]
[1] "plot"

[[11]]
[1] "[1] \"after: 3\"\n[1] \"before: 4\"\n"

[[12]]
[1] "call: 5"

[[13]]
[1] "plot"

[[14]]
[1] "[1] \"after: 4\"\n[1] \"before: 5\"\n"

[[15]]
[1] "plot"

[[16]]
[1] "[1] \"after: 5\"\n"
```

**Comment by janschulz** [comment]
I added https://github.com/hadley/evaluate/issues/67 for this issue...
