### ISSUE TITLE
on mac Terminal R sends me to miniconda version instead of regular R

### ISSUE THREAD

**Issue by data-steve** [IRkernel/IRkernel#325]
I've tried to install and get IRKernel up and running on jupyter via miniconda install plus other essentials

same old rzmq errors that everyone else talks about in the issues here.

But now when I want to ignore IRKernel and go on, I find my R in the Terminal is now linked to miniconda version which is 3.2.2, even though I'm running 3.2.4 now.

```
devmac60osx:~ ssimpson$ which R
/Users/ssimpson/miniconda3/bin/R
```

I have done the `conda uninstall -c r r` to get rid of it, but R in terminal is still linked to 3.2.2 miniconda version.

How to unlink totally, please?

Thanks

**Comment by takluyver** [comment]
Either remove it (if it's still showing up in the output of `which`, you haven't removed it), or change the order of things on your `$PATH` so that the R you want is first.

If you've fully removed it and you can't start R from the shell because it's still trying to run the missing file, your shell has cached the location. Close the terminal and open a new one. Or, if you need to keep the same shell, run `hash -r` to clear bash's cache.
