### ISSUE TITLE
print buffering is not easy to control

### ISSUE THREAD

**Issue by tentrillion** [IRkernel/IRkernel#351]
Using an R GUI or just R from a command line, the loop below results in integers being printed 0.2 seconds apart.

In contrast when I use R in a jupyter notebook, all of the printing happens only after the loop is complete.

    for(x in 1:10){
        print(x)
        Sys.sleep(0.2)
    }

I tried to force real-time printing inside of Jupyter with

    for(x in 1:10){
        print(x)
        flush.console()
        Sys.sleep(0.2)
    }

...to no effect.  The results were the same -- printing from within a for loop in jupyter always seems to be delayed until after the loop.

On the advice of [a question on this topic I put on Stack Overflow](http://stackoverflow.com/questions/37689694/real-time-printing-to-console-with-r-in-jupyter), I decided to file an issue here.

**Comment by takluyver** [comment]
Yep, see #3. We can't easily fix it in IRkernel, because we're relying on the evaluate package. There's [a plan](https://github.com/jupyter/enhancement-proposals/pull/14) to implement something in Jupyter to capture stdout at the OS level, which would make this easier, but it has got mired in discussion.

**Comment by janschulz** [comment]
@takluyver I think as long as we use evaluate we won't solve this problem **without** a fix in evaluate: I don't think we can make `evaluate` print the output when it happens so that it could be captured by a nanny... For that to work we would have to get a new way to evaluate/execute code.

BTW: I thought the nanny plan had reached some consensus? Seems my impression was wrong :-)

**Comment by takluyver** [comment]
> I thought the nanny plan had reached some consensus?

We had consensus at the dev meeting, then I put the proposal online and a whole new discussion started. I still hope to make it happen, but I haven't had the time and energy to push it through.

**Comment by janschulz** [comment]
I've now reread the proposal and as far as I can see, you answered all questions/concerns... :-) I'm really looking forward to see a kernel nanny wrapping IRkernel on windows, so that IRkernel can be killed properly :-)
