### ISSUE TITLE
Export logging utilities to enable usage in upstream projects

### ISSUE THREAD

**Issue by poplav** [IRkernel/IRkernel#369]
* We are working on improving logging/error message handling on the kernel side of declarative widgets (https://github.com/jupyter-incubator/declarativewidgets/pull/419).
* Instead of bringing in another logging package we would like to use what is already in IRkernel.  The [jupyter_options](https://github.com/IRkernel/IRkernel/blob/master/NAMESPACE#L5) for controlling the log level and log file are exported (so I can do `options(jupyter.log_level = 2L)`), but not the actual logging utilities [log_(debug|info|error)](https://github.com/IRkernel/IRkernel/blob/master/R/logging.r#L5).  Am I missing something or can I open a PR to export these?

**Comment by janschulz** [comment]
IMO the only reason was that I saw no reason for them to be exported (and actually saw no other package to depend on IRkernel). If you have a use case, it's no problem to have them exported.  Do you need them in the user session or as a real dependency?

The only thing would be that IMO they should get a prefix if they are in any way visible to the user (`.irk_log_debug` if in the [user env](https://github.com/IRkernel/IRkernel/blob/master/R/environment.r#L15) or `irkernel_log_debug` if exported) to not interfere with outer logging frameworks: I really don't want to get bugreports of users using a logging framework in their regular work and getting these functions mixed up or even only seeing messages that some functions are shadowed due to name overlap.

**Comment by poplav** [comment]
@janschulz 
My use case is to use these logging utilities instead of needing to bring my own additional/separate logging framework in.  I can control the level and log file options simply as well, so this works out well when I tested it.
If #370 looks good can you merge it.  Thanks.

**Comment by janschulz** [comment]
How do you use irkernel? as a package dependency or in the user session? (I've no real clue how declarative widgets work...)

**Comment by poplav** [comment]
Declarative widgets is a library we load as part of a notebook session in the irkernel

**Comment by flying-sheep** [comment]
before we go on: why are there and functions added via `add_to_user_searchpath` which are *not* overrides of internals? `.irk.get_shadowenv` and so on could simply be exported instead.

i’d say there’s a few classes of functions:

* kernel installation and managing functions: `installspec` and `Kernel$run()`
* runtime functions regarding display: in the `IRdisplay` package
* runtime functions (other kinds): currently added to the user search path

i think we shouldn’t pollute the search path even with hidden functions and just export `get_shadowenv`.

**Comment by poplav** [comment]
@flying-sheep , we can do that, I mean I see merits with both approaches.  Exporting those functions makes it more intuitive imo.  Let me know or we can merge this in and clean up the environment on another commit.

**Comment by flying-sheep** [comment]
hmm, everything we export needs to be documented and is there to stay.

if you’re OK with later changing your code when we decide to export it instead, we can merge the PR as is (apart from the unnecessary `@include`)

**Comment by poplav** [comment]
@flying-sheep , If you don't mind can we merge as is and i'll pin to a commit/update when the discussion finalizes regarding environment issues.
