### ISSUE TITLE
Is it a bug that a list of date displays as NULL in R Jupyter notebook?

### ISSUE THREAD

**Issue by DavidBriant** [IRkernel/IRkernel#380]
`list(as.Date("2016-05-02"))` displays as NULL.

How do I fix this or request for it to be fixed pls?

Thx

**Comment by flying-sheep** [comment]
primitive vector reprs are handled [here](https://github.com/IRkernel/repr/blob/master/R/repr_vector.r)

the best way to fix this is to

1. for every format (replace `*` by `latex`, `markdown`, …) add the following [here](https://github.com/IRkernel/repr/blob/master/R/repr_vector.r):

	```r
	#' @name repr_*.vector
	#' @export
	repr_*.Date <- repr_*.logical
	```

3. add to the tests

 it would be nice to create a special `repr_html.Date` function that wraps every list item like `\t<li><time datetime="%s">%s</time></li>\n`, but that’s a bit complicated because using `%s` twice requires code changes.
