### ISSUE TITLE
LICENSE file doesn't contain usable license information

### ISSUE THREAD

**Issue by tylere** [IRkernel/IRkernel#389]
What license is IRKernel being released under? The [current license file](https://github.com/IRkernel/IRkernel/blob/master/LICENSE) provides copyright info, but does not actually declare a license.

**Comment by flying-sheep** [comment]
MIT.

and that’s the way R packages work. look into DESCRIPTION, please

**Comment by takluyver** [comment]
FWIW, I agree that it's crazy to have a file called 'license' that doesn't actually include a license.

**Comment by flying-sheep** [comment]
agreed. but if we go this route: i rather have *no* file called LICENSE

**Comment by takluyver** [comment]
Having a regular LICENSE file is nice because it provides a language-independent way to see the license of a repository. There are tools that do fuzzy matching on license files to collect data on license usage, for instance.

Also, the MIT license says that redistributors have to include the copyright and permissions notice that's usually in the LICENSE file. Many other licenses have a similar provision. So if one were [really picky](https://www.debian.org/), I think you'd have to add the license in to redistribute IRkernel in compliance with the license.

**Comment by flying-sheep** [comment]
funny: this means that IRkernel can’t be on CRAN and in debian both

**Comment by takluyver** [comment]
If Debian really is that picky, they can add the license and be in compliance. But it seems polite for upstreams to put it in there.

**Comment by tylere** [comment]
Thanks.
R's convention seems non-intuitive, but at least there is a standard
convention for the community. That's good enough for my needs.
