### ISSUE TITLE
htmltools 

### ISSUE THREAD

**Issue by epifanio** [IRkernel/IRkernel#392]
I was experimenting the usage of `rglwidgets` and/or  `htmltools` with `threejs` in R, I succesfully tested the following example in rstudio-server, so I guess their implementation in IRkernel should be possible.

Trying to run both on a jupyter notebook with IRkernel installed from git master, i got the  following:
- [rglwidgets](http://www.htmlwidgets.org/showcase_rglwidget.html)

``` R
library(rgl)
library(rglwidget)
library(htmltools)

theta <- seq(0, 6*pi, len=100)
xyz <- cbind(sin(theta), cos(theta), theta)
lineid <- plot3d(xyz, type="l", alpha = 1:0, 
                 lwd = 5, col = "blue")["data"]

browsable(tagList(
  rglwidget(elementId = "example", width = 500, height = 400,
            controllers = "player"),
  playwidget("example", 
             ageControl(births = theta, ages = c(0, 0, 1),
                        objids = lineid, alpha = c(0, 1, 0)),
             start = 1, stop = 6*pi, step = 0.1, 
             rate = 6,elementId = "player")
))
```

which return the error:

```
Warning message:
In rgl.init(initValue, onlyNULL): RGL: unable to open X11 displayWarning message:
: 'rgl_init' failed, running with rgl.useNULL = TRUE
```
- [htmltools](http://blog.revolutionanalytics.com/2015/05/a-first-look-at-htmlwidgets.html)

``` R
library(stringr)
library(htmltools)
library(threejs)
data(mtcars) 
data <- mtcars[order(mtcars$cyl),] 
head(data)

uv <- tabulate(mtcars$cyl)
col <- c(rep("red",uv[4]),rep("yellow",uv[6]),rep("blue",uv[8]))
row.names(mtcars)

scatterplot3js(data[,c(3,6,1)],
               labels=row.names(mtcars),    # mousing over a point will show what model car it is
               size=mtcars$hp/100,          # the size of a point maps to horsepower
               flip.y=TRUE,
               color=col,renderer="canvas") # point color indicates num
```

which doesn't print any log/error for the `scatterplot3js` call.

Is there any plan to enable the use of those library on jypyter R kernel?

**Comment by takluyver** [comment]
I guess it's some object that needs a repr method? @flying-sheep do you know anything about the library in question?

**Comment by janschulz** [comment]
Re the second example (no idea on the first error):

rthreejs seems to be htmlwidgets based. In this case we might get luck by implementing a `repr_html.htmlwidget` (and `repr_text_htmlwidget` which just prints that you need html enabled to view it -> it needs to be more than "nothing") because the function [seems to directly returns a htmlwidget](https://github.com/bwlewis/rthreejs/blob/0b5718d3a00c0d44e7d8b2d6584376f068b32803/R/scatterplot.R#L296).


But there is still the problem that a lot of htmlwidget bases packages return an object of their own and that most packages implement only a print method for their package which converts the to be printed object to a html widget and then call print on that method (an example is [formattable](https://github.com/renkun-ken/formattable/blob/c772c81f31d21b1e2ae3b7fbfa517d47ab1100e8/R/formattable.R#L202-L204)). RStudio implements a `print.htmlwidget` which saves the widget to a file and then displays it. 

The easy way out would be to add a similar implementation in IRkernel (which would be triggered by plain text repr method). The alternatives are much more work: we either implement a `repr_html.<objecttype>` for all the different objects which can be converted to a htmlwidget or we ask upstream to implement such a method (which [didn't really work out in pander](http://tinyurl.com/zscujkc)).

**Comment by flying-sheep** [comment]
we already have [`repr_`{`html`,`text`}`.htmlwidget`](https://irkernel.github.io/docs/repr/0.9/repr_-times-.htmlwidget.html9

**Comment by flying-sheep** [comment]
about the first one:

```r
> class(browsable(...))
'shiny.tag.list' 'list' 
> htmltools:::print.shiny.tag.list
function (x, browse = is.browsable(x), ...) 
{
    if (browse) 
        html_print(x)
    else print(HTML(as.character(x)), ...)
    invisible(x)
}
> # is.browsable(browsable(...)) is obviously true
> htmltools:::html_print
function (html, background = "white", viewer = getOption("viewer", 
    utils::browseURL)) 
{
    www_dir <- tempfile("viewhtml")
    dir.create(www_dir)
    index_html <- file.path(www_dir, "index.html")
    save_html(html, file = index_html, background = background, 
        libdir = "lib")
    if (!is.null(viewer)) 
        viewer(index_html)
    invisible(index_html)
}
```

so here we could simply set `options(viewer = function(html_path))`…

**Comment by flying-sheep** [comment]
```r
repr_html.shiny.tag.list <- function(o) {
    paste(lapply(repr_html, o), collapse = '\n')
}
```

**Comment by flying-sheep** [comment]
here is everything collected: https://gist.github.com/flying-sheep/d3d4e636729957d6fe5d93b14a4ee72f

**Comment by epifanio** [comment]
Running on a headless server with no desktop environment it give the worning about missing X display, but the widget works just fine, It works great! 
It is so nice to have RGL in a notebook cell. Thank you!

**Comment by flying-sheep** [comment]
cool! i still plan to put this into repr tho, so let’s leave this open

**Comment by flying-sheep** [comment]
it’s been in repr for some time
