### ISSUE TITLE
Requires stringr package

### ISSUE THREAD

**Issue by nick5435** [IRkernel/IRkernel#395]
Just letting you know that from a fresh install of R/RStudio, the stringr package is not installed, and thus the dox on [the Installation page](https://irkernel.github.io/installation/) is not up-to-date.

**Comment by flying-sheep** [comment]
we don’t use it. i guess some of our recursive dependencies or devtools uses it, so it’s a bug there.

do you know more about it?

**Comment by takluyver** [comment]
It's a declared dependency of `evaluate`, but `evaluate` is not in that list. I think it should be, so I'll add it to the instructions.

**Comment by takluyver** [comment]
(How you end up with evaluate but not `stringr`, I'm not sure, though...)

**Comment by takluyver** [comment]
I spotted a couple more missing dependencies as well - see if it works now:
https://irkernel.github.io/installation/

**Comment by takluyver** [comment]
I can't currently reproduce the original problem, so I'm not sure if that change to the instructions has fixed it or not.

**Comment by nick5435** [comment]
I have no clue. I was able to resolve it just by installing the stringr package.

**Comment by takluyver** [comment]
The only thing I can think of is that the Rstudio installation is shipping with `evaluate`, but without `stringr`, even though it's a dependency, so evaluate is broken even before you install IRkernel.

Are you on Windows? @hafizurcse who reported this as #393 is on Windows. If that's the common factor, it would be good for someone on Windows to do a fresh install of Rstudio, and then see if `library(evaluate)` works.

**Comment by lwahedi** [comment]
I can confirm that this is still a problem. I updated R with installr, then followed the directions to install IRkernel using devtools. It failed at stringr. It worked after installing stringr, however. This was on Windows 10. I may move this project over to a Linux Docker soon. If I have trouble there too I'll let you know. 

I can also confirm that I started with evaluate, but that may be because update in installr moves your packages over. @nick5435 how did you install the updated version of R? I wonder if it has something to do with jumping from version to version, and stringr getting lost on the way. 

Also as a side note, installing IRkernel from cran didn't work, I got an error saying it wasn't available for R version 3.3.2.

**Comment by flying-sheep** [comment]
yes, IRkernel is not on CRAN. we’re working on it (@takluyver: i fixed those NOTEs, let’s resubmit)

devtools maybe has a bug with dependency resolution, or some package depending on stringr didn’t mention it as dependency. that’s not something we can change

**Comment by nick5435** [comment]
@lwahedi I migrated to using [AnacondaR][Anaconda R] and Microsoft R Open. If you're already using Anaconda's `conda` for Python, you can simply do `conda config --add channels mro` to add the Microsoft R Open to the channels list (or do `conda config --add channels r` if you just want vanilla, non-accelerated R). Then you can install R from conda by doing `conda install r r-essentials`, which will even install IRKernel!

Hopefully you find this helpful.


[AnacondaR]: https://docs.continuum.io/anaconda/r_language
