### ISSUE TITLE
IRKernel Update

### ISSUE THREAD

**Issue by spennihana** [IRkernel/IRkernel#503]
Hi IRkernel folks!

I'll keep this short but:

Lately, I've been playing a lot with Rcpp and jupyter purely out of curiosity, and I think I've come up with a pretty interesting project: https://github.com/JuniperKernel/JuniperKernel.

I want to see if there's room for collaboration here as I'm realizing that many of our problems overlap.

**Comment by flying-sheep** [comment]
Hi, so that’s an alternative R kernel?

What are the differences? What are the problems you solve that we don’t and the other way round?

Anyway, if you didn’t do it already, I’d advise you to use repr, it was quite some work. Then, we solved many, many fiddly issues you’ll encounter in time. Make sure you check out our solution to problems when you encounter them.

**Comment by takluyver** [comment]
@spennihana definitely picked a cooler name than us 😄

**Comment by spennihana** [comment]
ya! It's a month old, so it hasn't got everything a complete kernel would have. Main difference here is that all of the zmq bits are written in C++.

One interesting thing that it does is stdout/stderr to be streamed to the client on-demand (so issues such as #494   don't surface).

It's missing plots (which seems like a sore spot here in IRkernel as well!!), a few message types, comms, and that's just the tip of me looking at what needs to be implemented. For plots, I am considering either forking or using svglite with custom callbacks in the device -- I think there's an issue floating around here regarding implementing a device from scratch... Even without the custom callbacks, the svglite interface will dump out a string that could be rasterized in the client.

Lots of issues to sort out! Lots of fun stuff; wanted to make myself and the project aware :)

**Comment by flying-sheep** [comment]
> One interesting thing that it does is stdout/stderr to be streamed to the client on-demand

yes, that’s certainly a weak point here.

> It's missing plots (which seems like a sore spot here in IRkernel as well!!)

they generally work fine here! there’s some glitches in mapping the R concept of plot devices and pages to static outputs like jupyter has, but nothing too problematic (there’s only some rather rare discrepancies when using traditional plots: `points`/`lines` and so on).

**Comment by takluyver** [comment]
We did have some display issues with svg plots as well, but I think that's all sorted now (the key was to make sure they were properly isolated on the page so the styles didn't affect one another)

**Comment by flying-sheep** [comment]
i’m a big fan of SVG plots, their quality is impossible to reach with raster images. there are some practical problems, however:

- other parts of jupyter and the ecosystem used to be (and partly still are) buggy around SVG (i loved using SVG by default because we uncovered so many bugs elsewhere!)
- once you have too much going on in a plot, browsers get slowed down. mainly firefox. i think once firefox 57 hits (it’s much faster), i’m reactivating SVG by defaut.

**Comment by takluyver** [comment]
There's always going to be some scale where serialising everything to be drawn in the frontend (as SVG does) is impractical. For interactive use, things like Bokeh or the matplotlib notebook backend can do a better job by dynamically requesting the necessary data as you pan & zoom. But then it needs extra code to get a plot that can be used in a static document.

My suspicion is that PNG is likely to remain as the default, because it's the most robust option. But it should be easy for people to switch to SVG if they want it.

**Comment by flying-sheep** [comment]
> But then it needs extra code to get a plot that can be used in a static document.

oh, you mean just send a HTML payload with the dynamic plot and also a SVG/PNG payload with a static one in the same mimebundle?

why didn’t i think of this? rbokeh, plotly and so on usually have `class(p) == c('rbokeh', 'htmlwidget')`, so just providing a `repr_svg.rbokeh` would be enough here.

**Comment by spennihana** [comment]
I haven't looked too deeply into rbokeh; but it looks like you get the full data + stand-alone html/js/css widget

For the first pass here I think the svglite fork is working out. It sounds like I will ultimately want to convert to png for static plots, though.
