### ISSUE TITLE
Export to html/view in nbviewer: plotly-graphs do not show

### ISSUE THREAD

**Issue by Thriceguy** [IRkernel/IRkernel#541]
I am trying to share a notebook with collaborators, but the graphs created with _plotly_ do not show up in either exported html, or when viewing the notebook on _nbviewer_ (it works with equivalent code on a ipython-kernel which makes me think it has to do with the IRkernel).

Example code:
```
library(plotly)
set.seed(123)

x <- rnorm(1000)
y <- rchisq(1000, df = 1, ncp = 0)
plot_ly(y = y, x = x, 
        type = 'scatter', mode='markers',
        width = 950, height = 500, hoverinfo = 'x+y+text')
```

This shows up just fine in my local notebook, but the plotting area is blank in an html-file generated with the _download as_ option, and the same holds true for loading the notebook in _nbviewer_. 

This behaviour does not change if I include the following line at the beginning of my notebook, and restart the kernel

`options(jupyter.plot_mimetypes = c("text/plain", "image/png" ))`

as suggested [here](http://compbio.ucsd.edu/outputting-beautiful-jupyter-notebooks-r-kernel-edition/).

Notably (or perhaps not), this produces html-output which displays correctly:

```
library(plotly)
set.seed(123)

x <- rnorm(1000)
y <- rchisq(1000, df = 1, ncp = 0)
p <- plot_ly(y = y, x = x, 
        type = 'scatter', mode='markers',
        width = 950, height = 500, hoverinfo = 'x+y+text')

htmlwidgets::saveWidget(p, "index.html")
```
Any idea what is going on here, and how I can fix it?

Versions:
IRkernel: 0.8.12.9000
plotly: 4.7.1
jupyter notebook: 5.4.0

**Comment by Konstantin-Lasiy** [comment]
I'm getting the same problem. It used to work fine before, but it's not working anymore. Not sure what changed.

**Comment by takluyver** [comment]
I don't follow IRkernel development closely enough these days to know, but have you looked at where the plot should be in your browser's DOM inspector? What turns up there?

**Comment by rommelnc** [comment]
I am having the same issue. Any news on this?

**Comment by anthonymakela** [comment]
Did anyone find out a solution for this?

**Comment by flying-sheep** [comment]
works fine for me with the newest IRkernel, IRdisplay, and repr.

if it doesn’t for you, we need more info, e.g. what @takluyver said

**Comment by anthonymakela** [comment]
@flying-sheep Here you can see the notebook.  https://nbviewer.jupyter.org/github/anthonymakela/Traffic-accidents-Finland/blob/master/traffic_accident_analysis_finland.ipynb

**Comment by anthonymakela** [comment]
@flying-sheep Here you can see the notebook. https://nbviewer.jupyter.org/github/anthonymakela/Traffic-accidents-Finland/blob/master/traffic_accident_analysis_finland.ipynb

**Comment by flying-sheep** [comment]
please create a minimal example. one cell, as few and short lines as possible.

**Comment by anthonymakela** [comment]
This is the output from sessionInfo. The current version of IRkernel im running seems to be 0.8.12 and the newest release is 0.8.14 but i assume that's not the cause of the problem here?

`R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] C/UTF-8/C/C/C/C

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] bindrcpp_0.2.2    IRdisplay_0.7.0   forecast_8.4      plotly_4.8.0     
 [5] memisc_0.99.14.12 gridExtra_2.3     repr_0.18         zoo_1.8-3        
 [9] lubridate_1.7.4   dplyr_0.7.6       DMwR_0.4.1        lattice_0.20-35  
[13] MASS_7.3-51.1     data.table_1.11.4 readr_1.1.1       ggplot2_3.0.0    

loaded via a namespace (and not attached):
 [1] nlme_3.1-137         bitops_1.0-6         xts_0.11-1          
 [4] httr_1.3.1           tools_3.5.1          R6_2.2.2            
 [7] rpart_4.1-13         KernSmooth_2.23-15   lazyeval_0.2.1      
[10] colorspace_1.3-2     nnet_7.3-12          withr_2.1.2         
[13] tidyselect_0.2.4     curl_3.2             compiler_3.5.1      
[16] labeling_0.3         tseries_0.10-45      caTools_1.17.1.1    
[19] scales_1.0.0         lmtest_0.9-36        fracdiff_1.4-2      
[22] quadprog_1.5-5       pbdZMQ_0.3-3         stringr_1.3.1       
[25] digest_0.6.18        foreign_0.8-70       rio_0.5.10          
[28] base64enc_0.1-3      pkgconfig_2.0.2      htmltools_0.3.6     
[31] htmlwidgets_1.3      rlang_0.2.2          readxl_1.1.0        
[34] TTR_0.23-3           quantmod_0.4-13      shiny_1.1.0         
[37] bindr_0.1.1          jsonlite_1.5         crosstalk_1.0.0     
[40] gtools_3.8.1         zip_1.0.0            car_3.0-2           
[43] magrittr_1.5         Rcpp_0.12.19         IRkernel_0.8.12.9000
[46] munsell_0.5.0        abind_1.4-5          yaml_2.2.0          
[49] stringi_1.2.4        carData_3.0-2        gplots_3.0.1        
[52] plyr_1.8.4           parallel_3.5.1       gdata_2.18.0        
[55] promises_1.0.1       forcats_0.3.0        crayon_1.3.4        
[58] haven_1.1.2          hms_0.4.2            pillar_1.3.0        
[61] uuid_0.1-2           urca_1.3-0           glue_1.3.0          
[64] evaluate_0.12        httpuv_1.4.5         cellranger_1.1.0    
[67] gtable_0.2.0         purrr_0.2.5          tidyr_0.8.1         
[70] assertthat_0.2.0     openxlsx_4.1.0       mime_0.5            
[73] xtable_1.8-3         uroot_2.0-9          later_0.7.5         
[76] class_7.3-14         viridisLite_0.3.0    timeDate_3043.102   
[79] tibble_1.4.2         ROCR_1.0-7          
repr
'0.18'
IRdisplay
'0.7.0'
IRkernel
'0.8.12.9000'`

**Comment by anthonymakela** [comment]
@flying-sheep These are the versions from sessionInfo. Im currently running IRkernel 0.8.12 and the newest versions seems to be 0.8.14, but i assume that's not the cause of the problem here?

repr
'0.18'
IRdisplay
'0.7.0'
IRkernel
'0.8.12.9000'

**Comment by flying-sheep** [comment]
just try it, it might be.

**Comment by anthonymakela** [comment]
Unfortunately, the problem persists. Any other ideas 😄?

**Comment by anthonymakela** [comment]
@flying-sheep This should be a rather simple example. Everything works perfectly when I'm running it locally but as soon as i use nbviewer the plot's only displaying blank. https://nbviewer.jupyter.org/gist/anthonymakela/8814d01476a9b4c3751b67844f4c925d

**Comment by flying-sheep** [comment]
![grafik](https://user-images.githubusercontent.com/291575/49439803-51081380-f7c2-11e8-867f-18895b7c8d8e.png)

**Comment by anthonymakela** [comment]
Updated the link.

**Comment by anthonymakela** [comment]
@flying-sheep Updated the link.

**Comment by flying-sheep** [comment]
aha! It’s a bug in the nbviewer. The notebook contains

```json
{
  "data": {
    "application/vnd.plotly.v1+json": "...",
    "text/html": ["..."],
    "text/plain": [ "HTML widgets cannot be represented in plain text (need html)" ]
  },
  "metadata": {
    "text/html": { "isolated": true }
  },
}
```

here “isolated: true” means that the content is a complete website, not a HTML fragment. but the nbviewer’s website source just slaps it in there:

```html
<div class="output_area">
<div class="prompt"></div>
<div class="output_html rendered_html output_subarea ">

<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
                <script src="..."></script>
                ...
	</head>
        <body>
                ...
        </body>
</html>

</div>
</div>
</div>
```

which is of course wrong and not valid HTML. please report the bug there.

**Comment by takluyver** [comment]
I think this is a symptom of https://github.com/jupyter/nbconvert/issues/129

**Comment by anthonymakela** [comment]
@takluyver If you have any advice on how to bypass this it would be very appreciated.

**Comment by takluyver** [comment]
I don't, sorry.

**Comment by pakinja** [comment]
Hello. I have the problem that when I export the notebook to html the plotly objects appear in blank.

![ir1](https://user-images.githubusercontent.com/15304390/54882849-e8ea4580-4e23-11e9-9c33-c5eb3478d0df.png)

In the notebook they appear normally.

![ir2](https://user-images.githubusercontent.com/15304390/54882853-edaef980-4e23-11e9-8e72-fb40294f7124.png)

**Comment by flying-sheep** [comment]
I don’t think this is a IRkernel bug. Can you file this in https://github.com/jupyter/nbconvert and CC me  (just write “CC @flying-sheep”)

Please also attach a minimal notebook illustrating the problem there.

**Comment by djacob65** [comment]
@Thriceguy, @Konstantin-Lasiy,   @rommelnc  @takluyver @anthonymakela 

Here is a solution which works for me - Use the IRdisplay::display method with the good options:

library(plotly)
library(IRdisplay)
x <- 1:100
y <- rnorm(100)
p <- plot_ly(x=x, y=y) %>% add_markers()

options(jupyter.plot_mimetypes = c("text/html", "image/svg+xml" ))
display(p)


Versions:
repr  '1.0.1'
IRdisplay '0.7.0'
IRkernel '1.0.2'
plotly '4.9.0'

**Comment by JoaoMatheusHneda** [comment]
Here is another solution which works for me. Save the plotly chart as widget/html and use display_html.

library(datasets)
library(ggplot2)
g1  <- ggplot(aes(x=speed,y=dist),data=cars) + geom_point() + geom_smooth()

library(plotly)
g1_plotly <- ggplotly(g1)

library(htmlwidgets)
library(IRdisplay)
saveWidget(as_widget(g1_plotly), "g1_plotly.html")
display_html('<iframe src="g1_plotly.html" width=100%, height=400></iframe>') # IRdisplay can only be used from the IPython R kernel and R magic.
