### ISSUE TITLE
HTML widgets now print `<!DOCTYPE html>` 

### ISSUE THREAD

**Issue by terhorst** [IRkernel/IRkernel#549]
This just started happening, so I assume it's related to a recent change.

```
library(stringr)
options(jupyter.rich_display=T)
x = c("apple", "banana", "pear")
str_view(x, '[be]a')
```
This displays:
![image](https://user-images.githubusercontent.com/18204/37064552-6ba4a98e-216b-11e8-88dc-7f300f39d967.png)

Previously, it printed the correct output but without the DOCTYPE.

**Comment by terhorst** [comment]
Also: I'm not really sure where this report should go. The problem may well lie with IRkernel/repr or htmlwidgets.

**Comment by flying-sheep** [comment]
cannot reproduce, it works fine with the newest versions

**Comment by 1rdsk1** [comment]
How can I get the str_view as shown in code above to work in Jupyter please?  I copied that code to my R jupyter notebook and ran it (Firefox browser) but nothing displayed whereas the aboce screen shot show same output as I'd get in the Rstudio viewer?

**Comment by flying-sheep** [comment]
do you have newest IRkernel, IRdisplay, repr? if not, please update, restart and rerun the notebook. It should work.

**Comment by 1rdsk1** [comment]
Thankd but I followed your instructions by reinstalling the three software mentioned.  Still the stringr functions do not display in Jupyter but work fine in Rstudio.
I run Jupyter via Conda.
My versions just updated are:
r  / packages / r-irkernel 0.8.12
r  / packages / r-irdisplay 0.5.0
r  / packages / r-repr 0.15.0
![capture](https://user-images.githubusercontent.com/16118846/52428034-1475d280-2af9-11e9-9bcb-b1f279c85e56.PNG)

**Comment by 1rdsk1** [comment]
Thanks. Yes. HTML for both rstudio and Jupyter.  But the str_view cells in Jupyter still dont work.

![image](https://user-images.githubusercontent.com/16118846/52428521-0d9b8f80-2afa-11e9-9362-c523a24e6aa4.png)

**Comment by flying-sheep** [comment]
I’ll explain:

1. If `getOption('jupyter.rich_display')` is TRUE, IRkernel tries to create more-than-text representations of stuff.
2. It calls `repr::mime2repr[[mime]]` for each mime type in `getOption('jupyter.display_mimetypes')`
3. That option by default contains `'text/html'`, and `repr::mime2repr[['text/html']]` is `repr::repr_html`
4. If that function now returns text instead of NULL and the options are set correctly, IRkernel works and isn’t at fault if you can’t see anything.
5. Therefore

    ```r
    if (
        getOption('jupyter.rich_display') &&
        'text/html' %in% getOption('jupyter.display_mimetypes') &&
        !is.null(repr::repr_html(your_object))
    ) {
        shit_should_work()
    }
    ```

You can also try saving the notebook, opening it with a text editor and checking if its JSON contains `"outputs": [..., { "data": { ..., "text/html": "..." } }, ...]` for those cells.

**Comment by 1rdsk1** [comment]
Many thanks.  

Please do you know how long before these newer versions will make their way onto Conda?

**Comment by flying-sheep** [comment]
No idea! I’m not involved with anaconda in any way. But can’t you just install CRAN packages into your conda env?

**Comment by 1rdsk1** [comment]
Packages yes.  But I dont know about the IRkernel used in Jupyter.  Will have to do more digging on that.
