### ISSUE TITLE
Suppress backticks in tab completion for paths

### ISSUE THREAD

**Issue by byerancy** [IRkernel/IRkernel#626]
Before submitting an issue please be sure to answer these questions with **yes**:

- [x] Did you follow the [official installation instructions](https://irkernel.github.io/installation/)?
Yes
- [x] Did you reproduce the error with the newest versions? If the following code installs packages, you didn’t yet!
Yes, I'm currently using the latest versions.
- [x] Did you include a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)?
Yes, pls see below.
- [x] Is this the right repository?
I'm not quite sure it's a display problem or something else...

Hi,

I'm wondering if it's possible to suppress the backticks when use tab completion for path? For now I have to manually remove them after select one.
<img width="605" alt="屏幕快照 2019-05-06 下午11 51 18" src="https://user-images.githubusercontent.com/12895451/57237725-62e43000-705a-11e9-987e-06895187ed67.png">
<img width="594" alt="屏幕快照 2019-05-06 下午11 51 33" src="https://user-images.githubusercontent.com/12895451/57237728-637cc680-705a-11e9-960e-77224c231d4e.png">
Many thanks!

**Comment by flying-sheep** [comment]
Hi! I just redid the completion to be more useful for everything except strings and left this a TODO:

https://github.com/IRkernel/IRkernel/blob/9134e35e59903972355aedd7d88cb84849840181/R/completion.r#L40

I’m currently a bit busy, so if you want to help, please just play around with that file and try if you can make it skip “fixing up” string completions. Here are the tests that currently pass:

https://github.com/IRkernel/IRkernel/blob/9134e35e59903972355aedd7d88cb84849840181/tests/testthat/test_ir.py#L48-L58

**Comment by byerancy** [comment]
Glad to try to make some contributions! Thanks for the tips!

**Comment by flying-sheep** [comment]
Sure! If you have questions about the code (or anything really), just shoot.

**Comment by olliecast** [comment]
Hi,

I've also been having this issue. Have you found any solutions to date?

Many thanks

**Comment by flying-sheep** [comment]
@byerancy tries his/her hand at this (see https://github.com/IRkernel/IRkernel/issues/626#issuecomment-490040272) and you could do the same.

**Comment by olliecast** [comment]
I can also have a go but I'm afraid I'm rather new to computational work (< 1 year) so please excuse my naive questions:

1) What is the intended purpose of wrapping strings with backticks? Could see it's to wrap non-identifiers (which is a new concept to me; I've had a quick read of the link you left) but why would one want these to be wrapped in backticks as a function of the autocomplete instead of just wrapping them manually as you would the quotations or brackets for example? 

2) In the short period of time I've been writing code I use tab completion for pathway completion more than anything else while the backticks appear to serve a niche purpose (From what I could understand from this thread https://stackoverflow.com/questions/36220823/what-do-backticks-do-in-r). Of course this may be something unique to myself and more experienced programmers may find it more helpful how it is now. Could it be an idea to leave strings un-wrapped by default then check for if it's a reserved or illegal string before wrapping? Alternatively if there's the presence of back or forward slashes to assume it's a path?

I would attempt to implement these myself but I'm not really sure how to start. I'm also not so familiar with regex expressions so struggling a bit to get the meaning of some of the pattern searches. 

Thank you for your time, any pointers & information on this area would be really helpful.

**Comment by flying-sheep** [comment]
There’s no purpose, it’s a bug. I traded that bug for another bug, namely that identifiers with illegal characters didn’t get completed. I personally complete paths far less often than e.g. data frame column names with illegal characters, or so, but of course both those and paths should work.

To fix this, you’ll have to change not (only) the `completions` function, because it just gets passed a character vector containing the file names, no info if we’re in a string. I think a valuable heuristic is to basically parse the code in the `code` or `line` variable. I think this regex is able to find if the given code ends with an unfinished string:

```regex
^                    (?# start of the line/code )
(
    "(\\.|[^"\\])*"  (?# double quote string )
  | '(\\.|[^'\\])*'  (?# or a single quote string )
  | [^"']+           (?# or stuff that isn’t a string )
)*                   (?# zero or more of those 3 options )
["']                 (?# one quote character )
[^"']+               (?# followed only by non-quote characters )
$                    (?# end of the line/code )
```

You have to detect that, and then skip calling `fixup` if this is the case.

Then you’d add some examples to `completion_samples` that show this works.

**Comment by olliecast** [comment]
Ah I see, makes sense.

I'm afraid it's beyond my current understanding and I can't spare the time at the moment to learn/ attempt. I've reverted to a previous version for now hopefully someone with more know-how can tackle it!

Appreciate the help. Thank you!

**Comment by FrancisBlokzijl** [comment]
Hi,

I'm experiencing the same issue. Should I revert to an older version of IRkernel?

Thanks!
Francis

**Comment by flying-sheep** [comment]
There’s important bug fixes in newer versions, so I’d not recommend that.

You could try doing that PR to fix it!

**Comment by FrancisBlokzijl** [comment]
Okay, thanks. Any other suggestions?

**Comment by flying-sheep** [comment]
You could clone this repo change this line:

https://github.com/IRkernel/IRkernel/blob/719bbf5e2e6c463532a54a88655fc0bd9a4aed19/R/completion.r#L29

to 

```r
if (fixup && !grepl('["\']', line)) comps <- fixup_comps(comps) 
```

and install it, then it’ll leave the completions alone if the line contains a `'` or `"`

**Comment by flying-sheep** [comment]
Hi, if anyone wants to test this, I just pushed c2c5e798449fc721462b599f2650a7633d7fc0b9.

Can you please do `devtools::install_github('IRkernel/IRkernel')` and report if this works?

**Comment by FrancisBlokzijl** [comment]
Hi! I tested it but unfortunately I had the same issue. I did this:

```
library(devtools)
devtools::install_github('IRkernel/IRkernel')
library("IRkernel")
IRkernel::installspec() # I tried both with and without this command 
```
Is this correct?

And then auto completion still looks like this with backticks:

![image](https://user-images.githubusercontent.com/7942300/71087226-f575b180-219b-11ea-8cdf-cfbc8ca6a949.png)

Thanks for you effort!

Best,
Francis

**Comment by flying-sheep** [comment]
Looks like this for me:

![grafik](https://user-images.githubusercontent.com/291575/71156793-fb719e00-2240-11ea-9ed4-3b72f6829345.png)

You need to restart the kernel before the new version is active, either with the <kbd>↻</kbd> button or by shutting down your jupyter notebook process and restarting that (restarting all kernels in the process)

Unrelated: I recommend Jupyter Lab instead of Jupyter Notebook.

PS: neither `library("IRkernel")` nor `IRkernel::installspec()` is needed, and if you call a function using `some.module::*`, there’s no need to do `library(some.module)` beforehand

**Comment by FrancisBlokzijl** [comment]
Yes it works! Thank you so much! This will make my life easier :-)

And thanks for the general tips! I will check out Jupyter Lab, what is the advantage over notebook?

**Comment by flying-sheep** [comment]
Great! I’m happy that this worked for you and I think I’ll soon release a new version with this small fix in it.

About Jupyter Lab: It’s the successor, so everything is a bit more elegant and user friendly. Basically it’s what the people who made the notebook interface wanted to make all along. The main advantage is that there’s no more browser tabs for individual notebooks, all’s in one interface: File browser, open notebooks, extension manager, …
