### ISSUE TITLE
Dataframe dimensions and column datatypes are printed on screen

### ISSUE THREAD

**Issue by apcamargo** [IRkernel/IRkernel#628]
In the newest version of IRkernel (1.0.1), when a matrix or a dataframe is shown in the output, a string containing the datatype and the dimensions is printed above the table itself. Also, the datatype of the columns are now being shown under the column.

![Screenshot from 2019-05-09 09 52 08](https://user-images.githubusercontent.com/22940964/57454836-23773880-7240-11e9-9c34-60c2b2c759dd.png)

I'm unsure if this change was done by design. If it was, please ignore this bug.

Thanks!

**Comment by flying-sheep** [comment]
Yes, that’s a feature! Why do you think it’s a bug? :wink:

**Comment by apcamargo** [comment]
I like this feature! I was unsure if this is recommended because it differs from the IPython implementation.

**Comment by flying-sheep** [comment]
Uh, what do you mean “recommended”?

**Comment by apcamargo** [comment]
I thought IPython was a reference implementation

**Comment by flying-sheep** [comment]
No, why? Every kernel can do whatever its authors think is useful.

E.g. I decided that in R, every expression in a cell will be displayed, not just the last one. I did it that way because R has `invisible(expr)` to say that something shouldn’t be displayed.

And I found `tibble`’s output useful, so I implemented it for all `data.frames`. Maybe IPython will start doing that too, maybe not, who knows.
