### ISSUE TITLE
SoS environment: Interrupted R kernel stops functioning

### ISSUE THREAD

**Issue by MatteoSchiavinato** [IRkernel/IRkernel#629]
I have been using the [SoS](https://vatlab.github.io/sos-docs/) (script of scripts) implementation for Jupyter Notebook since some months, using pyhton3, R and bash kernels. While with pyhton3 and bash kernels I can perform all the actions that the notebook allows the user to do, with the R kernel I have an issue: every time that, for any reason, I interrupt the kernel manually, I cannot use any R cell anymore in the notebook until I restart the whole SoS kernel. 

I am posting this here, and not in the SoS page, since it happens only with the ir-kernel. 

Is this a known issue for you? Anything that I could try to sort this out?

**Comment by flying-sheep** [comment]
Never head about SoS :sweat_smile: 

In the regular environment, interruptions work as they should, and starting from v0.8.9, interrupts to the kernel while it’s idle stopped killing it (771c6fb5309d6bd0fc162a73058ebc59dda46389).

So no idea what happens here!

Try starting the whole shebang with the environment variable `JUPYTER_LOG_LEVEL` set to 3 and tell me what happens when you interrupt both a kernel that’s currently running some R code and one that’s idle.

**Comment by MatteoSchiavinato** [comment]
I tried but the kernel issue is quite erratic, does not happen always and so it is hardly reproducible. It might be an SoS problem, so perhaps I'm closing this issue and contacting the SoS team directly.

**Comment by flying-sheep** [comment]
OK! come back whenever you have something I can investigate
