### ISSUE TITLE
IRkernel::installspec fails when there is a space in OSX user name

### ISSUE THREAD

**Issue by D-Bishop** [IRkernel/IRkernel#647]
I'm running R from the terminal, on OSX
My username has a space in it (lastname firstname)
No, I can't change this; it's a corporately managed machine (and we know it's unwise/dumb but it's out of my control)

IRkernel::installspec fails, and it seems apparent that it's because the space isn't getting passed through correctly...

```
> IRkernel::installspec(user=FALSE)
/Library/Developer/CommandLineTools/usr/bin/objdump: 'firstname/Library/R/3.6/library/pbdZMQ/libs/libzmq.5.dylib': No such file or directory
Error: .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: if (id[2] != fn.dylib) {
  error: missing value where TRUE/FALSE needed
In addition: Warning message:
In system(paste(cmd.ot, " -D ", fn.dylib, sep = ""), intern = TRUE) :
  running command '/usr/bin/otool -D /Users/lastname firstname/Library/R/3.6/library/pbdZMQ/libs/libzmq.5.dylib' had status 1
>
```

**Comment by flying-sheep** [comment]
I don’t think it’s dumb, I like spaces in names. We no longer live in the 90s, people should make their stuff work with legal file names. This means:

- Shell languages that explode string variables are outdated. People should use scripting languages or modern shells like Fish or Ion or so. If one has to work with Bash or Zsh, one should always make sure to use variables `"$only_in_quotes"`.
- I consequently haven’t produced a bug like this in years so this isn’t my bug.

Check the message: The error happens because `.onLoad failed in loadNamespace() for 'pbdZMQ'`, so please report your bug there.
