### ISSUE TITLE
There are not other language in locale  R kernel in Jupyter Lab!

### ISSUE THREAD

**Issue by heemokyim** [IRkernel/IRkernel#650]
I linked to Jupyternotebook to use the R kernel, 
but no other languages ​​exist except English. In detail, 
there was only 'C' in locale. What should I do?

![image](https://user-images.githubusercontent.com/29696458/73248747-e0f2f300-41f6-11ea-93a7-eb2516cc17b2.png)

**Comment by flying-sheep** [comment]
Cannot reproduce. There’s nothing in IRkernel that prevents the normal locale from applying: It simply starts an R process and runs some code in it that replies to jupyter lab’s messages.

The error is most likely because you’re using another R in the kernel than the one you’re used to. You can get the R binary via:

```console
$ jupyter kernelspec list --json | jq -r '.kernelspecs.ir.spec.argv[0]'
/usr/lib64/R/bin/R
```

If that’s not the one you want to use, open the kernel.json in the directory returned by

```console
$ jupyter kernelspec list --json | jq -r '.kernelspecs.ir.resource_dir'
~/.local/share/jupyter/kernels/ir
```

If you don’t have `jq`, just search the paths in the JSON returned by `jupyter kernelspec list --json` yourself
